# Generated by Django 3.2.8 on 2021-10-08 18:52

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anniversary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='data', null=True)),
                ('description', models.TextField(blank=True, db_column='descricao', null=True)),
                ('invitation', models.FileField(blank=True, db_column='convite', null=True, upload_to='convites/')),
                ('catalog', models.FileField(blank=True, db_column='catalogo', null=True, upload_to='catalogos/')),
            ],
            options={
                'db_table': 'galeria_aniversario',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nome', max_length=100)),
                ('thumbnail', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True)),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'geral_foto',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nome', max_length=200)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'publicacoes_link',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nome', max_length=50)),
                ('image', models.ImageField(blank=True, db_column='imagem', null=True, upload_to='inicial/')),
                ('text', models.TextField(blank=True, db_column='texto', null=True)),
                ('text_en', models.TextField(blank=True, db_column='texto_en', null=True)),
                ('url', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(db_column='visivel', default=False)),
                ('ordering', models.SmallIntegerField(db_column='ordem')),
            ],
            options={
                'db_table': 'geral_destaque',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='titulo', max_length=500)),
                ('text', models.TextField(blank=True, db_column='texto', null=True)),
                ('text_en', models.TextField(blank=True, db_column='texto_en', null=True)),
            ],
            options={
                'db_table': 'publicacoes_texto',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='titulo', max_length=200)),
                ('author', models.CharField(blank=True, db_column='autor', max_length=100, null=True)),
                ('editor', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_type', models.CharField(choices=[('Catalogo', 'Catalogo'), ('Imprensa', 'Imprensa'), ('Critica', 'Critica')], db_column='tipo', max_length=10)),
                ('date', models.DateField(blank=True, db_column='data', null=True)),
                ('description', models.TextField(blank=True, db_column='descricao', null=True)),
                ('description_en', models.TextField(blank=True, db_column='descricao_en', null=True)),
                ('file', models.FileField(blank=True, db_column='ficheiro', max_length=200, null=True, upload_to='publicacoes/')),
                ('artist', models.ForeignKey(blank=True, db_column='artista_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='art.artist')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'db_table': 'publicacoes_publicacao',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nome', max_length=200)),
                ('description', models.TextField(blank=True, db_column='descricao', null=True)),
                ('street', models.CharField(blank=True, db_column='rua', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='cidade', max_length=30, null=True)),
                ('zip_code', models.CharField(blank=True, db_column='cod_postal', max_length=8, null=True)),
                ('phone', models.CharField(blank=True, db_column='telefone', max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=75, null=True)),
                ('opening_times', models.CharField(blank=True, db_column='horario', max_length=200, null=True)),
                ('map', models.URLField(blank=True, db_column='mapa', null=True)),
                ('fotos', models.ManyToManyField(blank=True, db_table='galeria_galeria_fotos', to='gallery.Foto')),
            ],
            options={
                'db_table': 'galeria_galeria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='titulo', max_length=200)),
                ('exhibition_type', models.CharField(blank=True, choices=[('I', 'Individual'), ('C', 'Colectiva')], db_column='tipo', max_length=1)),
                ('description', models.TextField(blank=True, db_column='descricao', null=True)),
                ('description_en', models.TextField(blank=True, db_column='descricao_en', null=True)),
                ('start_date', models.DateField(db_column='data_inicio', verbose_name='data de inicio')),
                ('end_date', models.DateField(db_column='data_fim', verbose_name='data de fim')),
                ('invitation', models.FileField(blank=True, db_column='convite', null=True, upload_to='convites/')),
                ('press_release', models.FileField(blank=True, null=True, upload_to='press_releases/')),
                ('art_type', models.ManyToManyField(db_table='exposicoes_exposicao_tipo_arte', to='art.ArtType')),
                ('art_works', models.ManyToManyField(blank=True, db_table='exposicoes_exposicao_obras', to='art.ArtWork')),
                ('artists', models.ManyToManyField(blank=True, db_table='exposicoes_exposicao_artistas', to='art.Artist')),
                ('canvases', models.ManyToManyField(db_table='exposicoes_exposicao_telas', to='art.Canvas')),
                ('catalog', models.ForeignKey(blank=True, db_column='catalogo_id', limit_choices_to={'tipo__exact': 'Catalogo'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.publication')),
                ('fotos', models.ManyToManyField(blank=True, db_table='exposicoes_exposicao_fotos', to='gallery.Foto')),
                ('galleries', models.ManyToManyField(db_table='exposicoes_exposicao_galerias', to='gallery.Gallery')),
            ],
            options={
                'verbose_name': 'Exposição',
                'verbose_name_plural': 'Exposições',
                'db_table': 'exposicoes_exposicao',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Awardee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nome', max_length=150)),
                ('profession', models.CharField(blank=True, db_column='profissao', max_length=50, null=True)),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.foto')),
            ],
            options={
                'db_table': 'galeria_premiado',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nome', max_length=150)),
                ('description', models.TextField(blank=True, db_column='descricao', null=True)),
                ('anniversary', models.ForeignKey(blank=True, db_column='aniversario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.anniversary')),
                ('awardee', models.ForeignKey(blank=True, db_column='premiado_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.awardee')),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.foto')),
            ],
            options={
                'db_table': 'galeria_premio',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='anniversary',
            name='fotos',
            field=models.ManyToManyField(blank=True, db_table='galeria_aniversario_fotos', to='gallery.Foto'),
        ),
        migrations.AddField(
            model_name='anniversary',
            name='trophy',
            field=models.ForeignKey(blank=True, db_column='trofeu_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='art.artwork'),
        ),
    ]
