# Generated by Django 2.2.19 on 2021-04-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_auto_20210403_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
