# Generated by Django 2.2.19 on 2021-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artistas", "0002_auto_20210329_1344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artista",
            name="biografia",
            field=models.FileField(blank=True, null=True, upload_to="biografias/"),
        ),
    ]
