# Generated by Django 2.2.19 on 2021-04-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destaque',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='inicial/'),
        ),
        migrations.AlterField(
            model_name='tela',
            name='image',
            field=models.ImageField(upload_to='geral/'),
        ),
    ]
