# Generated by Django 3.2 on 2021-10-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0002_auto_20210403_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tecnica',
            options={'ordering': ['nome'], 'verbose_name': 'Técnica', 'verbose_name_plural': 'Técnicas'},
        ),
    ]
