# Generated by Django 2.2.19 on 2021-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='ficheiro',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='publicacoes/'),
        ),
    ]
