# Generated by Django 2.2.19 on 2021-04-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0002_auto_20210403_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='tipo',
            field=models.CharField(choices=[('Catalogo', 'Catalogo'), ('Imprensa', 'Imprensa'), ('Critica', 'Critica')], max_length=10),
        ),
    ]
