# Generated by Django 3.2 on 2021-10-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0003_auto_20210417_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'ordering': ['-data'], 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
    ]
