# Generated by Django 3.2.8 on 2021-10-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gallery", "0001_initial"),
        ("art", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="foto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gallery.foto",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="materials",
            field=models.ManyToManyField(
                blank=True, db_table="artistas_obra_materiais", to="art.ArtMaterial"
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="techniques",
            field=models.ManyToManyField(
                blank=True, db_table="artistas_obra_tecnicas", to="art.ArtTechnique"
            ),
        ),
        migrations.AddField(
            model_name="arttechnique",
            name="category",
            field=models.ForeignKey(
                db_column="categoria_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="art.arttype",
            ),
        ),
        migrations.AddField(
            model_name="artmaterial",
            name="category",
            field=models.ForeignKey(
                db_column="categoria_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="art.arttype",
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="art_type",
            field=models.ManyToManyField(
                db_table="artistas_artista_tipo", to="art.ArtType"
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="canvases",
            field=models.ManyToManyField(
                blank=True, db_table="artistas_artista_telas", to="art.Canvas"
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="foto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foto",
                to="gallery.foto",
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="foto_art_work",
            field=models.ForeignKey(
                db_column="foto_obra_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foto_obra",
                to="gallery.foto",
            ),
        ),
    ]
