# Generated by Django 2.2.19 on 2021-04-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exposicoes', '0002_auto_20210329_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposicao',
            name='catalogo',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__exact': 'Catalogo'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicacoes.Publicacao'),
        ),
        migrations.AlterField(
            model_name='exposicao',
            name='convite',
            field=models.FileField(blank=True, null=True, upload_to='convites/'),
        ),
        migrations.AlterField(
            model_name='exposicao',
            name='press_release',
            field=models.FileField(blank=True, null=True, upload_to='press_releases/'),
        ),
    ]
